### ISSUE TITLE
图片在线管理问题

### ISSUE THREAD

**Issue by willhunger** [zhangfisher/DjangoUeditor#73]
有一个分支下的https://github.com/wsqy/DjangoUeditor
再点击图片在线管理问题后,出现如下错误:

> Internal Server Error: /ueditor/controller/
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
>     return view_func(*args, **kwargs)
>   File "/home/will/PycharmProjects/hnwcd/DjangoUeditor/views.py", line 63, in get_ueditor_controller
>     return reponseAction[action](request)
>   File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
>     return view_func(*args, **kwargs)
>   File "/home/will/PycharmProjects/hnwcd/DjangoUeditor/views.py", line 92, in list_files
>     files = get_files(root_path, root_path, allowFiles[action])
>   File "/home/will/PycharmProjects/hnwcd/DjangoUeditor/views.py", line 116, in get_files
>     item = unicode(item)
> NameError: name 'unicode' is not defined

**Comment by willhunger** [comment]
请问该如何解决??
